import json

# ================= 設定區 =================
# 輸入：你的 JSON 檔案
JSON_FILES = {
    "model": "polyhaven_models_catalog.json",      # 請確認檔名正確
    "hdri": "polyhaven_scene_catalog.json",        # 請確認檔名正確
    "texture": "polyhaven_textures_catalog.json"   # 請確認檔名正確
}

# 輸出：生成的 SQL 檔案名稱
OUTPUT_SQL_FILE = "polyhaven_data.sql"
# =========================================

def escape_sql_string(value):
    """處理 SQL 字串跳脫，將 ' 轉為 '' 以避免錯誤，處理 None"""
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"

def generate_sql():
    print(f"🚀 正在生成 SQL 檔案: {OUTPUT_SQL_FILE} ...")
    
    with open(OUTPUT_SQL_FILE, "w", encoding="utf-8") as out_sql:
        # 寫入檔頭
        out_sql.write("-- PolyHaven Data Import SQL\n")
        out_sql.write("-- Generated by Python Script\n\n")
        out_sql.write("BEGIN;\n\n")  # 開啟交易

        for asset_type, json_path in JSON_FILES.items():
            print(f"   📂 處理 {json_path} ...")
            try:
                with open(json_path, 'r', encoding='utf-8') as f:
                    data = json.load(f)
            except FileNotFoundError:
                print(f"   ⚠️ 找不到 {json_path}，跳過。")
                continue

            # 相容性處理：有的 JSON 是 list (items)，有的是 dict (assets)
            if "items" in data:
                 assets_dict = { item["id"]: item for item in data["items"] }
            else:
                 assets_dict = data.get("assets", {})
            
            for external_id, content in assets_dict.items():
                meta = content.get("meta", {})
                files_tree = content.get("files", {})
                
                name = meta.get("name", external_id)
                # 處理 JSON 內的單引號，避免 SQL 語法錯誤
                raw_json = json.dumps(content).replace("'", "''")
                
                # -------------------------------------------------------
                # 1. 生成 Asset Library 插入語句
                # -------------------------------------------------------
                out_sql.write(f"""-- Asset: {name}
INSERT INTO asset_library (external_id, name, source, asset_type, raw_api_data)
VALUES ({escape_sql_string(external_id)}, {escape_sql_string(name)}, 'polyhaven', '{asset_type}', '{raw_json}')
ON CONFLICT (source, external_id) DO NOTHING;
""")

                # -------------------------------------------------------
                # 2. 生成 Categories 插入語句
                # -------------------------------------------------------
                for cat in meta.get("categories", []):
                    cat_sql = escape_sql_string(cat)
                    out_sql.write(f"""INSERT INTO categories (name) VALUES ({cat_sql}) ON CONFLICT DO NOTHING;
INSERT INTO asset_categories (asset_id, category_id)
SELECT id, (SELECT id FROM categories WHERE name = {cat_sql})
FROM asset_library WHERE external_id = {escape_sql_string(external_id)} AND source = 'polyhaven'
ON CONFLICT DO NOTHING;
""")

                # -------------------------------------------------------
                # 3. 生成 Tags 插入語句
                # -------------------------------------------------------
                for tag in meta.get("tags", []):
                    tag_sql = escape_sql_string(tag)
                    out_sql.write(f"""INSERT INTO tags (name) VALUES ({tag_sql}) ON CONFLICT DO NOTHING;
INSERT INTO asset_tags (asset_id, tag_id)
SELECT id, (SELECT id FROM tags WHERE name = {tag_sql})
FROM asset_library WHERE external_id = {escape_sql_string(external_id)} AND source = 'polyhaven'
ON CONFLICT DO NOTHING;
""")

                # -------------------------------------------------------
                # 4. 生成 Asset Downloads 插入語句 (攤平 JSON)
                # -------------------------------------------------------
                # 先刪除舊的
                out_sql.write(f"""DELETE FROM asset_downloads WHERE asset_id = (SELECT id FROM asset_library WHERE external_id = {escape_sql_string(external_id)});
""")

                for component, resolutions in files_tree.items():
                    # === [修正點] 判斷是否為特殊的 "tonemapped" 或 "colorchart" 結構 ===
                    # 如果 resolutions 裡面直接有 'url'，代表它是單層結構，不是巢狀
                    if isinstance(resolutions, dict) and "url" in resolutions:
                        # 處理單層結構 (tonemapped, colorchart)
                        file_info = resolutions
                        url = file_info.get("url")
                        if not url: continue
                        
                        size = file_info.get("size", "NULL")
                        md5 = escape_sql_string(file_info.get("md5"))
                        
                        out_sql.write(f"""INSERT INTO asset_downloads (asset_id, component_type, resolution, file_format, url, file_size, md5_hash, include_map)
SELECT id, '{component}', 'preview', 'jpg', '{url}', {size}, {md5}, NULL
FROM asset_library WHERE external_id = {escape_sql_string(external_id)};
""")
                    
                    else:
                        # 處理標準三層結構 (Models, HDRIs, Backplates)
                        # Component -> Resolution -> Format
                        for resolution, formats in resolutions.items():
                            for fmt, file_info in formats.items():
                                url = file_info.get("url")
                                if not url: continue
                                
                                size = file_info.get("size", "NULL")
                                md5 = escape_sql_string(file_info.get("md5"))
                                
                                include_map = "NULL"
                                if "include" in file_info:
                                    include_map = "'" + json.dumps(file_info["include"]).replace("'", "''") + "'"

                                out_sql.write(f"""INSERT INTO asset_downloads (asset_id, component_type, resolution, file_format, url, file_size, md5_hash, include_map)
SELECT id, '{component}', '{resolution}', '{fmt}', '{url}', {size}, {md5}, {include_map}
FROM asset_library WHERE external_id = {escape_sql_string(external_id)};
""")
                
                out_sql.write("\n") # 空行分隔

        out_sql.write("COMMIT;\n") # 提交交易
    
    print(f"✅ 完成！SQL 檔案已產生於: {OUTPUT_SQL_FILE}")

if __name__ == "__main__":
    generate_sql()